### ISSUE TITLE
Small bug relating to PR #101

### ISSUE THREAD

**Issue by TomGeorge1234** [RatInABox-Lab/RatInABox#102]
@colleenjg relating to PR #101 

Sorry! After giving it the all clear I ran the tests and spotted an extra warning. If I just initialise a population of BVCs
```
Env = Environment()
Ag = Agent(Env)
BVCs = BoundaryVectorCells(Ag,params={'n':11})
```
it warns
```
UserWarning: Ignoring 'n' parameter value (11) that was passed, and setting number of BoundaryVectorCells neurons to 11, inferred from the cell arrangement parameter.
```

Sorry, I can dig into this in the morning but it might be quicker for you to solve.

**Comment by colleenjg** [comment]
Oh yes! That's because I was relying on the non-equality to raise the warning. I removed it quickly after our discussion without realizing that the decision to create the warning fully depends on it. And I didn't rerun my test code 😬

I'll fix it! Thanks for noticing it!
