### ISSUE TITLE
Agent vector cells 

### ISSUE THREAD

**Issue by TomGeorge1234** [RatInABox-Lab/RatInABox#88]
Hi @mehulrastogi when you get a chance can you push Agent vector cells as I want to make a figure to showcase them in the paper! 

Few comments: These will need to be Agent selective (not sure how you've done this right now), Agents have names which I guess could be used to specify which Agent the cells select for but I don't think these names are unique. We might need to give Agents a new `Agent.number` attribute which is guaranteed to be unique amongst all Agents in the same Environment.

**Comment by mehulrastogi** [comment]
yes, I have an agent_lookup code using the agent names (which need to be unique for each agent). I will add having an idx for the agent.
