### ISSUE TITLE
AgentVectorCells and FieldOfViewAVCs

### ISSUE THREAD

**Issue by sherryxia2016** [RatInABox-Lab/RatInABox#91]
Hi,

We're trying the notebooks in the demo folder and found the last notebook requires class AgentVectorCells and class FieldOfViewAVCs to be imported. However, we noticed these two are recently added classes and are only available in the dev branch. Can I know when they're ready to be pushed to the public package? Or can I install ratinabox from dev branch?

Thanks!

**Comment by TomGeorge1234** [comment]
You should be good to go!

```python
pip install --upgrade ratinabox
```

Here's the official release https://github.com/RatInABox-Lab/RatInABox/releases/tag/v1.11.0

**Comment by sherryxia2016** [comment]
Thanks a lot!!
